# Домашнее задание №5

### Задание №1 (1,5 балла)

Создайте два массива: в первом должны быть четные числа от 2 до 12 включительно, а в другом числа 7, 11, 15, 18, 23, 29.

$1.$ Сложите массивы и возведите элементы получившегося массива в квадрат:

In [19]:
import numpy as np
a = np.array([2, 4, 6, 8, 10, 12])
b = np.array([7, 11, 15, 18, 23, 29])
(a + b) ** 2

array([  81,  225,  441,  676, 1089, 1681], dtype=int32)

$2.$ Выведите все элементы из первого массива, которые стоят на тех местах, где элементы второго массива больше 12 и дают остаток 3 при делении на 5.

In [20]:
b[b>12]
a[np.arange(b.shape[0])%5==3]

array([8])

*3.* Для первого массива найдите остатки от деления на 2, а для второго --- на 3. Для каждого получившегося массива выведите его уникальные значения (см. семинар).

In [21]:
np.unique(a % 2)



array([0], dtype=int32)

In [22]:
np.unique(b % 3)

array([0, 1, 2], dtype=int32)

### Задание №2 (1,5 балла)

Найдите интересный для вас датасет. Например, можно выбрать датасет [тут](http://data.un.org/Explorer.aspx) или [тут](https://hls.harvard.edu/library/research/find-a-database/). Если выскакивают ошибки при считывании таблицы, попробуйте их погуглить и решить проблему!

1. Рассчитайте подходящие описательные статистики для признаков объектов в выбранном датасете
2. Проанализируйте и прокомментируйте содержательно получившиеся результаты
    - недостаточно написать фразы формата "Средний возраст = 60, а минимальный = 20", следует дать пояснение, что это значит и какие выводы можно сделать в рамках датасета
3. Все комментарии оформляйте строго в ячейках формата Markdown
    - для этого надо в выпадающем окошке сверху для текущей ячейки сменить тип Code на Markdown
    ![](https://i.imgur.com/vl7Fmg9.png)

In [29]:
dataset = np.loadtxt("123.txt", dtype=int)

In [30]:
dataset

array([[12, 18, 68, 98, 45],
       [45, 65, 48, 62, 42],
       [55, 66, 44, 88, 22],
       [98, 87, 65, 45, 32],
       [45, 65, 89, 52, 36]])

#### Медиана:

In [31]:
np.mean(dataset[:, 1])

60.2

#### Размах:

In [32]:
np.max(dataset[:, 0])-np.min(dataset[:, 0])

86

#### Дисперсия:

In [33]:
np.var(dataset[:, 3])

423.2